# Generated by Django 2.2.4 on 2019-09-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190901_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tiitle',
            new_name='title',
        ),
    ]
